// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRv-Wb0kOL2RdA4_Eati0r0LljKH2IBag',
    appId: '1:390068066972:web:c33008a9b59306b4c2ab59',
    messagingSenderId: '390068066972',
    projectId: 'qrcode-b8a5f',
    authDomain: 'qrcode-b8a5f.firebaseapp.com',
    storageBucket: 'qrcode-b8a5f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCixvnlpO-0LLbQ8XxEl49JH_7f4p-aXJY',
    appId: '1:390068066972:android:27a8a6c8ec917f19c2ab59',
    messagingSenderId: '390068066972',
    projectId: 'qrcode-b8a5f',
    storageBucket: 'qrcode-b8a5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbCKFX-ny49bQqS_TSiMifB3wagnF7fys',
    appId: '1:390068066972:ios:8361111a7fb373b9c2ab59',
    messagingSenderId: '390068066972',
    projectId: 'qrcode-b8a5f',
    storageBucket: 'qrcode-b8a5f.appspot.com',
    iosBundleId: 'com.example.qrCode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbCKFX-ny49bQqS_TSiMifB3wagnF7fys',
    appId: '1:390068066972:ios:e9f6c2fea5258e8ac2ab59',
    messagingSenderId: '390068066972',
    projectId: 'qrcode-b8a5f',
    storageBucket: 'qrcode-b8a5f.appspot.com',
    iosBundleId: 'com.example.qrCode.RunnerTests',
  );
}
